/* ============================================================
   ARAM MAYHEM INDICATOR — data.js
   ------------------------------------------------------------
   Données MOCKÉES pour le prototype.
   Structure pensée pour être remplacée plus tard par de vraies
   stats agrégées via l'API Riot Games (Match-V5) :
     - baseWinrate  -> winrate réel calculé sur X milliers de games
     - pickrate     -> fréquence de pick réelle
     - synergy      -> delta de winrate observé quand augments
                       combinés, calculé sur l'échantillon réel
   Pour l'instant tout est estimé "à la main" pour la démo.
   ============================================================ */

/* ddragonId = identifiant utilisé par le CDN Data Dragon de Riot
   pour l'URL de l'icône (souvent = name sans espace/apostrophe, quelques
   exceptions comme Wukong -> "MonkeyKing").
   Roster complété "à la main" à partir des connaissances générales du jeu —
   les champions sortis très récemment peuvent manquer, à vérifier/compléter
   au fil de l'eau. damageType/tags sont des approximations utiles au
   scoring (cf. script.js), pas une classification officielle Riot. */
const CHAMPIONS = [
  { id: "aatrox",      name: "Aatrox",       ddragonId: "Aatrox",      damageType: "AD",    tags: ["bruiser", "sustain", "healer"] },
  { id: "ahri",        name: "Ahri",         ddragonId: "Ahri",        damageType: "AP",    tags: ["mage", "burst", "mobile"] },
  { id: "akali",       name: "Akali",        ddragonId: "Akali",       damageType: "AP",    tags: ["assassin", "burst", "mobile"] },
  { id: "akshan",      name: "Akshan",       ddragonId: "Akshan",      damageType: "AD",    tags: ["marksman", "mobile"] },
  { id: "alistar",     name: "Alistar",      ddragonId: "Alistar",     damageType: "Mixed", tags: ["tank", "support", "cc-high", "engage"] },
  { id: "amumu",       name: "Amumu",        ddragonId: "Amumu",       damageType: "AP",    tags: ["tank", "cc-high", "aoe"] },
  { id: "anivia",      name: "Anivia",       ddragonId: "Anivia",      damageType: "AP",    tags: ["mage", "cc-high", "aoe"] },
  { id: "annie",       name: "Annie",        ddragonId: "Annie",       damageType: "AP",    tags: ["mage", "burst", "cc-high"] },
  { id: "aphelios",    name: "Aphelios",     ddragonId: "Aphelios",    damageType: "AD",    tags: ["marksman"] },
  { id: "ashe",        name: "Ashe",         ddragonId: "Ashe",        damageType: "AD",    tags: ["marksman", "cc-high"] },
  { id: "aurelionsol", name: "Aurelion Sol", ddragonId: "AurelionSol", damageType: "AP",    tags: ["mage", "aoe"] },
  { id: "azir",        name: "Azir",         ddragonId: "Azir",        damageType: "AP",    tags: ["mage", "poke"] },
  { id: "bard",        name: "Bard",         ddragonId: "Bard",        damageType: "AP",    tags: ["support", "cc-high"] },
  { id: "belveth",     name: "Bel'Veth",     ddragonId: "Belveth",     damageType: "Mixed", tags: ["fighter", "aoe"] },
  { id: "brand",       name: "Brand",        ddragonId: "Brand",       damageType: "AP",    tags: ["mage", "burst", "aoe"] },
  { id: "braum",       name: "Braum",        ddragonId: "Braum",       damageType: "AD",    tags: ["tank", "support", "cc-high"] },
  { id: "briar",       name: "Briar",        ddragonId: "Briar",       damageType: "AD",    tags: ["fighter", "sustain", "healer"] },
  { id: "caitlyn",     name: "Caitlyn",      ddragonId: "Caitlyn",     damageType: "AD",    tags: ["marksman", "poke"] },
  { id: "camille",     name: "Camille",      ddragonId: "Camille",     damageType: "AD",    tags: ["fighter", "mobile"] },
  { id: "cassiopeia",  name: "Cassiopeia",   ddragonId: "Cassiopeia",  damageType: "AP",    tags: ["mage", "poke"] },
  { id: "chogath",     name: "Cho'Gath",     ddragonId: "Chogath",     damageType: "AP",    tags: ["tank", "cc-high", "aoe"] },
  { id: "corki",       name: "Corki",        ddragonId: "Corki",       damageType: "Mixed", tags: ["marksman", "poke"] },
  { id: "darius",      name: "Darius",       ddragonId: "Darius",      damageType: "AD",    tags: ["bruiser", "sustain"] },
  { id: "diana",       name: "Diana",        ddragonId: "Diana",       damageType: "AP",    tags: ["fighter", "mobile", "aoe"] },
  { id: "drmundo",     name: "Dr. Mundo",    ddragonId: "DrMundo",     damageType: "AP",    tags: ["tank", "healer", "sustain"] },
  { id: "draven",      name: "Draven",       ddragonId: "Draven",      damageType: "AD",    tags: ["marksman"] },
  { id: "ekko",        name: "Ekko",         ddragonId: "Ekko",        damageType: "AP",    tags: ["assassin", "mobile", "burst"] },
  { id: "elise",       name: "Elise",        ddragonId: "Elise",       damageType: "AP",    tags: ["mage", "mobile"] },
  { id: "evelynn",     name: "Evelynn",      ddragonId: "Evelynn",     damageType: "AP",    tags: ["assassin", "burst", "mobile"] },
  { id: "ezreal",      name: "Ezreal",       ddragonId: "Ezreal",      damageType: "Mixed", tags: ["marksman", "mobile"] },
  { id: "fiddlesticks", name: "Fiddlesticks", ddragonId: "Fiddlesticks", damageType: "AP",  tags: ["mage", "cc-high", "aoe"] },
  { id: "fiora",       name: "Fiora",        ddragonId: "Fiora",       damageType: "AD",    tags: ["duelist", "mobile"] },
  { id: "fizz",        name: "Fizz",         ddragonId: "Fizz",        damageType: "AP",    tags: ["assassin", "mobile", "burst"] },
  { id: "galio",       name: "Galio",        ddragonId: "Galio",       damageType: "AP",    tags: ["tank", "cc-high", "aoe"] },
  { id: "gangplank",   name: "Gangplank",    ddragonId: "Gangplank",   damageType: "AD",    tags: ["fighter", "aoe"] },
  { id: "garen",       name: "Garen",        ddragonId: "Garen",       damageType: "AD",    tags: ["bruiser", "sustain", "tank"] },
  { id: "gnar",        name: "Gnar",         ddragonId: "Gnar",        damageType: "AD",    tags: ["fighter", "cc-high", "engage"] },
  { id: "gragas",      name: "Gragas",       ddragonId: "Gragas",      damageType: "AP",    tags: ["tank", "cc-high", "engage"] },
  { id: "graves",      name: "Graves",       ddragonId: "Graves",      damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "gwen",        name: "Gwen",         ddragonId: "Gwen",        damageType: "AP",    tags: ["fighter", "duelist"] },
  { id: "hecarim",     name: "Hecarim",      ddragonId: "Hecarim",     damageType: "AD",    tags: ["fighter", "cc-high", "engage", "aoe"] },
  { id: "heimerdinger", name: "Heimerdinger", ddragonId: "Heimerdinger", damageType: "AP",  tags: ["mage", "poke", "aoe"] },
  { id: "illaoi",      name: "Illaoi",       ddragonId: "Illaoi",      damageType: "AD",    tags: ["fighter", "sustain"] },
  { id: "irelia",      name: "Irelia",       ddragonId: "Irelia",      damageType: "AD",    tags: ["fighter", "mobile", "cc-high"] },
  { id: "ivern",       name: "Ivern",        ddragonId: "Ivern",       damageType: "AP",    tags: ["support", "shield"] },
  { id: "janna",       name: "Janna",        ddragonId: "Janna",       damageType: "AP",    tags: ["support", "shield", "cc-high"] },
  { id: "jarvaniv",    name: "Jarvan IV",    ddragonId: "JarvanIV",    damageType: "AD",    tags: ["fighter", "engage", "cc-high"] },
  { id: "jax",         name: "Jax",          ddragonId: "Jax",         damageType: "AD",    tags: ["fighter", "duelist"] },
  { id: "jayce",       name: "Jayce",        ddragonId: "Jayce",       damageType: "AD",    tags: ["fighter", "poke", "mobile"] },
  { id: "jhin",        name: "Jhin",         ddragonId: "Jhin",        damageType: "AD",    tags: ["marksman", "cc-high"] },
  { id: "jinx",        name: "Jinx",         ddragonId: "Jinx",        damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "kaisa",       name: "Kai'Sa",       ddragonId: "Kaisa",       damageType: "Mixed", tags: ["marksman", "mobile"] },
  { id: "kalista",     name: "Kalista",      ddragonId: "Kalista",     damageType: "AD",    tags: ["marksman", "mobile"] },
  { id: "karma",       name: "Karma",        ddragonId: "Karma",       damageType: "AP",    tags: ["mage", "support", "shield"] },
  { id: "karthus",     name: "Karthus",      ddragonId: "Karthus",     damageType: "AP",    tags: ["mage", "aoe", "poke"] },
  { id: "kassadin",    name: "Kassadin",     ddragonId: "Kassadin",    damageType: "AP",    tags: ["assassin", "mobile", "burst"] },
  { id: "katarina",    name: "Katarina",     ddragonId: "Katarina",    damageType: "AP",    tags: ["assassin", "burst", "aoe", "mobile"] },
  { id: "kayle",       name: "Kayle",        ddragonId: "Kayle",       damageType: "Mixed", tags: ["fighter", "aoe"] },
  { id: "kayn",        name: "Kayn",         ddragonId: "Kayn",        damageType: "AD",    tags: ["assassin", "mobile"] },
  { id: "kennen",      name: "Kennen",       ddragonId: "Kennen",      damageType: "AP",    tags: ["mage", "cc-high", "aoe"] },
  { id: "khazix",      name: "Kha'Zix",      ddragonId: "Khazix",      damageType: "AD",    tags: ["assassin", "mobile", "burst"] },
  { id: "kindred",     name: "Kindred",      ddragonId: "Kindred",     damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "kled",        name: "Kled",         ddragonId: "Kled",        damageType: "AD",    tags: ["fighter", "engage", "mobile"] },
  { id: "kogmaw",      name: "Kog'Maw",      ddragonId: "KogMaw",      damageType: "Mixed", tags: ["marksman", "aoe"] },
  { id: "leblanc",     name: "LeBlanc",      ddragonId: "Leblanc",     damageType: "AP",    tags: ["assassin", "burst", "mobile"] },
  { id: "leesin",      name: "Lee Sin",      ddragonId: "LeeSin",      damageType: "AD",    tags: ["fighter", "mobile", "engage"] },
  { id: "leona",       name: "Leona",        ddragonId: "Leona",       damageType: "AP",    tags: ["tank", "cc-high", "engage", "support"] },
  { id: "lillia",      name: "Lillia",       ddragonId: "Lillia",      damageType: "AP",    tags: ["mage", "aoe", "cc-high"] },
  { id: "lissandra",   name: "Lissandra",    ddragonId: "Lissandra",   damageType: "AP",    tags: ["mage", "cc-high"] },
  { id: "lucian",      name: "Lucian",       ddragonId: "Lucian",      damageType: "AD",    tags: ["marksman", "mobile"] },
  { id: "lulu",        name: "Lulu",         ddragonId: "Lulu",        damageType: "AP",    tags: ["support", "shield", "cc-high"] },
  { id: "lux",         name: "Lux",          ddragonId: "Lux",         damageType: "AP",    tags: ["mage", "poke", "cc-high"] },
  { id: "malphite",    name: "Malphite",     ddragonId: "Malphite",    damageType: "AP",    tags: ["tank", "engage"] },
  { id: "malzahar",    name: "Malzahar",     ddragonId: "Malzahar",    damageType: "AP",    tags: ["mage", "cc-high", "aoe"] },
  { id: "maokai",      name: "Maokai",       ddragonId: "Maokai",      damageType: "AP",    tags: ["tank", "cc-high", "engage"] },
  { id: "masteryi",    name: "Master Yi",    ddragonId: "MasterYi",    damageType: "AD",    tags: ["fighter", "mobile"] },
  { id: "milio",       name: "Milio",        ddragonId: "Milio",       damageType: "AP",    tags: ["support", "shield", "healer"] },
  { id: "missfortune", name: "Miss Fortune", ddragonId: "MissFortune", damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "mordekaiser", name: "Mordekaiser",  ddragonId: "Mordekaiser", damageType: "AP",    tags: ["fighter", "sustain"] },
  { id: "morgana",     name: "Morgana",      ddragonId: "Morgana",     damageType: "AP",    tags: ["mage", "cc-high", "shield"] },
  { id: "naafiri",     name: "Naafiri",      ddragonId: "Naafiri",     damageType: "AD",    tags: ["assassin", "mobile"] },
  { id: "nami",        name: "Nami",         ddragonId: "Nami",        damageType: "AP",    tags: ["support", "cc-high", "healer", "shield"] },
  { id: "nasus",       name: "Nasus",        ddragonId: "Nasus",       damageType: "AD",    tags: ["bruiser", "sustain", "healer"] },
  { id: "nautilus",    name: "Nautilus",     ddragonId: "Nautilus",    damageType: "AP",    tags: ["tank", "cc-high", "engage"] },
  { id: "neeko",       name: "Neeko",        ddragonId: "Neeko",       damageType: "AP",    tags: ["mage", "cc-high", "mobile"] },
  { id: "nidalee",     name: "Nidalee",      ddragonId: "Nidalee",     damageType: "AP",    tags: ["assassin", "mobile", "poke"] },
  { id: "nilah",       name: "Nilah",        ddragonId: "Nilah",       damageType: "AD",    tags: ["fighter", "healer", "aoe"] },
  { id: "nocturne",    name: "Nocturne",     ddragonId: "Nocturne",    damageType: "AD",    tags: ["assassin", "mobile", "cc-high"] },
  { id: "nunu",        name: "Nunu & Willump", ddragonId: "Nunu",      damageType: "AP",    tags: ["tank", "cc-high", "aoe"] },
  { id: "olaf",        name: "Olaf",         ddragonId: "Olaf",        damageType: "AD",    tags: ["fighter", "sustain"] },
  { id: "orianna",     name: "Orianna",      ddragonId: "Orianna",     damageType: "AP",    tags: ["mage", "cc-high", "aoe", "shield"] },
  { id: "ornn",        name: "Ornn",         ddragonId: "Ornn",        damageType: "AP",    tags: ["tank", "cc-high", "engage"] },
  { id: "pantheon",    name: "Pantheon",     ddragonId: "Pantheon",    damageType: "AD",    tags: ["fighter", "engage", "aoe"] },
  { id: "poppy",       name: "Poppy",        ddragonId: "Poppy",       damageType: "AD",    tags: ["tank", "cc-high", "engage"] },
  { id: "pyke",        name: "Pyke",         ddragonId: "Pyke",        damageType: "AD",    tags: ["assassin", "support", "cc-high", "mobile"] },
  { id: "qiyana",      name: "Qiyana",       ddragonId: "Qiyana",      damageType: "AD",    tags: ["assassin", "mobile", "cc-high"] },
  { id: "quinn",       name: "Quinn",        ddragonId: "Quinn",       damageType: "AD",    tags: ["marksman", "mobile"] },
  { id: "rakan",       name: "Rakan",        ddragonId: "Rakan",       damageType: "AP",    tags: ["support", "cc-high", "mobile", "shield"] },
  { id: "rammus",      name: "Rammus",       ddragonId: "Rammus",      damageType: "AD",    tags: ["tank", "cc-high", "engage"] },
  { id: "reksai",      name: "Rek'Sai",      ddragonId: "RekSai",      damageType: "AD",    tags: ["fighter", "mobile", "cc-high"] },
  { id: "rell",        name: "Rell",         ddragonId: "Rell",        damageType: "AP",    tags: ["tank", "cc-high", "engage"] },
  { id: "renata",      name: "Renata Glasc", ddragonId: "Renata",      damageType: "AP",    tags: ["support", "shield", "cc-high"] },
  { id: "renekton",    name: "Renekton",     ddragonId: "Renekton",    damageType: "AD",    tags: ["fighter", "sustain", "engage"] },
  { id: "rengar",      name: "Rengar",       ddragonId: "Rengar",      damageType: "AD",    tags: ["assassin", "mobile", "burst"] },
  { id: "riven",       name: "Riven",        ddragonId: "Riven",       damageType: "AD",    tags: ["fighter", "mobile"] },
  { id: "rumble",      name: "Rumble",       ddragonId: "Rumble",      damageType: "AP",    tags: ["fighter", "aoe"] },
  { id: "ryze",        name: "Ryze",         ddragonId: "Ryze",        damageType: "AP",    tags: ["mage", "poke", "mobile"] },
  { id: "samira",      name: "Samira",       ddragonId: "Samira",      damageType: "AD",    tags: ["marksman", "aoe", "mobile"] },
  { id: "sejuani",     name: "Sejuani",      ddragonId: "Sejuani",     damageType: "AP",    tags: ["tank", "cc-high", "engage", "aoe"] },
  { id: "senna",       name: "Senna",        ddragonId: "Senna",       damageType: "Mixed", tags: ["marksman", "support", "healer", "shield"] },
  { id: "seraphine",   name: "Seraphine",    ddragonId: "Seraphine",   damageType: "AP",    tags: ["mage", "support", "cc-high", "shield"] },
  { id: "sett",        name: "Sett",         ddragonId: "Sett",        damageType: "AD",    tags: ["fighter", "cc-high"] },
  { id: "shaco",       name: "Shaco",        ddragonId: "Shaco",       damageType: "AD",    tags: ["assassin", "mobile", "burst"] },
  { id: "shen",        name: "Shen",         ddragonId: "Shen",        damageType: "AD",    tags: ["tank", "shield", "engage"] },
  { id: "shyvana",     name: "Shyvana",      ddragonId: "Shyvana",     damageType: "Mixed", tags: ["fighter", "aoe", "mobile"] },
  { id: "singed",      name: "Singed",       ddragonId: "Singed",      damageType: "AP",    tags: ["tank", "sustain", "aoe"] },
  { id: "sion",        name: "Sion",         ddragonId: "Sion",        damageType: "AD",    tags: ["tank", "cc-high", "engage", "sustain"] },
  { id: "sivir",       name: "Sivir",        ddragonId: "Sivir",       damageType: "AD",    tags: ["marksman", "mobile", "aoe"] },
  { id: "skarner",     name: "Skarner",      ddragonId: "Skarner",     damageType: "AD",    tags: ["tank", "cc-high", "engage"] },
  { id: "smolder",     name: "Smolder",      ddragonId: "Smolder",     damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "sona",        name: "Sona",         ddragonId: "Sona",        damageType: "AP",    tags: ["support", "sustain", "healer"] },
  { id: "soraka",      name: "Soraka",       ddragonId: "Soraka",      damageType: "AP",    tags: ["support", "healer", "sustain"] },
  { id: "swain",       name: "Swain",        ddragonId: "Swain",       damageType: "AP",    tags: ["mage", "aoe", "cc-high", "healer"] },
  { id: "sylas",       name: "Sylas",        ddragonId: "Sylas",       damageType: "AP",    tags: ["fighter", "mobile", "cc-high"] },
  { id: "syndra",      name: "Syndra",       ddragonId: "Syndra",      damageType: "AP",    tags: ["mage", "cc-high", "burst"] },
  { id: "tahmkench",   name: "Tahm Kench",   ddragonId: "TahmKench",   damageType: "AP",    tags: ["tank", "sustain", "cc-high"] },
  { id: "taliyah",     name: "Taliyah",      ddragonId: "Taliyah",     damageType: "AP",    tags: ["mage", "mobile", "cc-high"] },
  { id: "talon",       name: "Talon",        ddragonId: "Talon",       damageType: "AD",    tags: ["assassin", "mobile", "burst"] },
  { id: "taric",       name: "Taric",        ddragonId: "Taric",       damageType: "AP",    tags: ["tank", "support", "shield", "cc-high", "healer"] },
  { id: "teemo",       name: "Teemo",        ddragonId: "Teemo",       damageType: "AP",    tags: ["marksman", "poke"] },
  { id: "thresh",      name: "Thresh",       ddragonId: "Thresh",      damageType: "AP",    tags: ["support", "cc-high", "engage"] },
  { id: "tristana",    name: "Tristana",     ddragonId: "Tristana",    damageType: "AD",    tags: ["marksman", "mobile", "aoe"] },
  { id: "trundle",     name: "Trundle",      ddragonId: "Trundle",     damageType: "AD",    tags: ["fighter", "sustain"] },
  { id: "tryndamere",  name: "Tryndamere",   ddragonId: "Tryndamere",  damageType: "AD",    tags: ["fighter", "sustain"] },
  { id: "twistedfate", name: "Twisted Fate", ddragonId: "TwistedFate", damageType: "AP",    tags: ["mage", "cc-high", "poke"] },
  { id: "twitch",      name: "Twitch",       ddragonId: "Twitch",      damageType: "AD",    tags: ["marksman", "aoe"] },
  { id: "udyr",        name: "Udyr",         ddragonId: "Udyr",        damageType: "Mixed", tags: ["fighter", "mobile"] },
  { id: "urgot",       name: "Urgot",        ddragonId: "Urgot",       damageType: "AD",    tags: ["fighter", "cc-high", "aoe"] },
  { id: "varus",       name: "Varus",        ddragonId: "Varus",       damageType: "Mixed", tags: ["marksman", "poke", "cc-high"] },
  { id: "vayne",       name: "Vayne",        ddragonId: "Vayne",       damageType: "AD",    tags: ["marksman", "true-damage"] },
  { id: "veigar",      name: "Veigar",       ddragonId: "Veigar",      damageType: "AP",    tags: ["mage", "burst", "cc-high"] },
  { id: "velkoz",      name: "Vel'Koz",      ddragonId: "Velkoz",      damageType: "AP",    tags: ["mage", "poke", "aoe"] },
  { id: "vex",         name: "Vex",          ddragonId: "Vex",         damageType: "AP",    tags: ["mage", "burst", "cc-high"] },
  { id: "vi",          name: "Vi",           ddragonId: "Vi",          damageType: "AD",    tags: ["fighter", "cc-high", "engage", "mobile"] },
  { id: "viego",       name: "Viego",        ddragonId: "Viego",       damageType: "AD",    tags: ["assassin", "mobile", "burst"] },
  { id: "viktor",      name: "Viktor",       ddragonId: "Viktor",      damageType: "AP",    tags: ["mage", "aoe", "cc-high"] },
  { id: "vladimir",    name: "Vladimir",     ddragonId: "Vladimir",    damageType: "AP",    tags: ["mage", "sustain", "healer", "aoe"] },
  { id: "volibear",    name: "Volibear",     ddragonId: "Volibear",    damageType: "Mixed", tags: ["bruiser", "engage"] },
  { id: "warwick",     name: "Warwick",      ddragonId: "Warwick",     damageType: "AD",    tags: ["bruiser", "healer", "sustain"] },
  { id: "wukong",      name: "Wukong",       ddragonId: "MonkeyKing",  damageType: "AD",    tags: ["fighter", "engage", "aoe", "mobile"] },
  { id: "xayah",       name: "Xayah",        ddragonId: "Xayah",       damageType: "AD",    tags: ["marksman", "aoe", "mobile"] },
  { id: "xerath",      name: "Xerath",       ddragonId: "Xerath",      damageType: "AP",    tags: ["mage", "poke", "cc-high", "aoe"] },
  { id: "xinzhao",     name: "Xin Zhao",     ddragonId: "XinZhao",     damageType: "AD",    tags: ["fighter", "engage", "cc-high"] },
  { id: "yasuo",       name: "Yasuo",        ddragonId: "Yasuo",       damageType: "AD",    tags: ["mobile", "duelist"] },
  { id: "yone",        name: "Yone",         ddragonId: "Yone",        damageType: "AD",    tags: ["fighter", "mobile", "aoe"] },
  { id: "yorick",      name: "Yorick",       ddragonId: "Yorick",      damageType: "AD",    tags: ["fighter", "sustain", "aoe"] },
  { id: "yuumi",       name: "Yuumi",        ddragonId: "Yuumi",       damageType: "AP",    tags: ["support", "healer", "shield"] },
  { id: "zac",         name: "Zac",          ddragonId: "Zac",         damageType: "AP",    tags: ["tank", "cc-high", "engage", "aoe", "sustain"] },
  { id: "zed",         name: "Zed",          ddragonId: "Zed",         damageType: "AD",    tags: ["assassin", "burst", "mobile"] },
  { id: "zeri",        name: "Zeri",         ddragonId: "Zeri",        damageType: "AD",    tags: ["marksman", "mobile"] },
  { id: "ziggs",       name: "Ziggs",        ddragonId: "Ziggs",       damageType: "AP",    tags: ["mage", "poke", "aoe"] },
  { id: "zilean",      name: "Zilean",       ddragonId: "Zilean",      damageType: "AP",    tags: ["support", "cc-high", "shield"] },
  { id: "zoe",         name: "Zoe",          ddragonId: "Zoe",         damageType: "AP",    tags: ["mage", "burst", "cc-high"] },
  { id: "zyra",        name: "Zyra",         ddragonId: "Zyra",        damageType: "AP",    tags: ["mage", "cc-high", "aoe"] },
];

/* ddragonId = id numérique officiel de l'objet (stable entre patches),
   utilisé pour l'URL de l'icône Data Dragon. */
const ITEMS = [
  { id: "randuins",    name: "Randuin's Omen",       ddragonId: 3143, type: "armor", tags: ["tank", "anti-crit"],          baseWinrate: 51.2 },
  { id: "thornmail",   name: "Thornmail",             ddragonId: 3075, type: "armor", tags: ["antiheal", "tank"],           baseWinrate: 52.8 },
  { id: "fon",          name: "Force of Nature",       ddragonId: 3111, type: "mr",    tags: ["tank", "mobility"],            baseWinrate: 50.4 },
  { id: "spiritvis",   name: "Spirit Visage",         ddragonId: 3065, type: "mr",    tags: ["healer", "tank"],              baseWinrate: 51.9 },
  { id: "ga",           name: "Guardian Angel",        ddragonId: 3026, type: "armor", tags: ["survivability"],               baseWinrate: 50.7 },
  { id: "maw",          name: "Maw of Malmortius",     ddragonId: 3156, type: "mr",    tags: ["ad", "shield"],                baseWinrate: 51.1 },
  { id: "banshee",     name: "Banshee's Veil",        ddragonId: 3102, type: "mr",    tags: ["shield", "ap"],                baseWinrate: 50.9 },
  { id: "frozenheart", name: "Frozen Heart",          ddragonId: 3110, type: "armor", tags: ["mana", "attackspeed-reduc"],  baseWinrate: 50.1 },
  { id: "zhonya",      name: "Zhonya's Hourglass",    ddragonId: 3157, type: "armor", tags: ["ap", "burst-survival"],       baseWinrate: 52.3 },
  { id: "merc",         name: "Mercurial Scimitar",    ddragonId: 3139, type: "mr",    tags: ["cleanse", "ad"],               baseWinrate: 51.6 },
  { id: "sunfire",     name: "Sunfire Aegis",         ddragonId: 3068, type: "armor", tags: ["tank", "aoe"],                 baseWinrate: 52.0 },
  { id: "warmogs",     name: "Warmog's Armor",        ddragonId: 3083, type: "hp",    tags: ["tank", "sustain"],             baseWinrate: 49.8 },
  { id: "witsend",     name: "Wit's End",              ddragonId: 3091, type: "mr",    tags: ["attackspeed", "ad"],           baseWinrate: 50.6 },
  { id: "adaptive",    name: "Adaptive Helm",         ddragonId: 3066, type: "mr",    tags: ["tank", "aoe-reduc"],           baseWinrate: 50.3 },
  { id: "deadmans",    name: "Dead Man's Plate",      ddragonId: 3742, type: "armor", tags: ["mobility", "tank"],            baseWinrate: 50.5 },
  { id: "exec",         name: "Executioner's Calling", ddragonId: 3123, type: "armor", tags: ["antiheal", "ad"],              baseWinrate: 49.5 },
  { id: "chempunk",    name: "Chempunk Chainsword",   ddragonId: 6609, type: "armor", tags: ["antiheal", "ad"],              baseWinrate: 50.2 },
  { id: "serpentsfang", name: "Serpent's Fang",       ddragonId: 6695, type: "armor", tags: ["anti-shield", "ad"],           baseWinrate: 49.9 },
  { id: "kaenic",      name: "Kaenic Rookern",        ddragonId: 4401, type: "mr",    tags: ["tank", "shield"],              baseWinrate: 51.4 },
  { id: "jaksho",      name: "Jak'Sho, The Protean",  ddragonId: 4633, type: "armor", tags: ["tank", "aoe-reduc"],           baseWinrate: 51.8 },
  { id: "abyssal",     name: "Abyssal Mask",          ddragonId: 8020, type: "mr",    tags: ["tank", "aoe"],                 baseWinrate: 50.8 },
  { id: "silvermere",  name: "Silvermere Dawn",       ddragonId: 6664, type: "mr",    tags: ["cleanse", "ad"],               baseWinrate: 50.9 },
  { id: "hollowradiance", name: "Hollow Radiance",    ddragonId: 3121, type: "mr",    tags: ["tank", "antiheal", "aoe"],     baseWinrate: 51.0 },
];

const AUGMENTS = [
  { id: "cheapskate",  name: "Radin de Guerre",   desc: "Réduction du coût des objets.",              tags: ["econ"],       baseWinrate: 50.5, synergy: {} },
  { id: "juggernaut",  name: "Juggernaut",         desc: "+HP et résistances massives.",               tags: ["tank"],       baseWinrate: 52.1, synergy: { fortification: 3.5, vampirism: 1.5 } },
  { id: "glasscannon", name: "Canon de Verre",    desc: "+Dégâts, -résistances.",                     tags: ["ap", "burst"],baseWinrate: 51.0, synergy: { arcanebolt: 4.0, adrenaline: 1.0 } },
  { id: "secondwind",  name: "Second Souffle",    desc: "Régénération accrue hors combat.",           tags: ["sustain"],    baseWinrate: 49.9, synergy: { vampirism: 2.0 } },
  { id: "electrocute", name: "Surcharge",          desc: "Dégâts bonus après 3 sorts touchés.",        tags: ["burst"],      baseWinrate: 51.4, synergy: { arcanebolt: 2.5 } },
  { id: "fortification", name: "Fortification",   desc: "+Armure et Résist. Magique.",                 tags: ["tank"],       baseWinrate: 52.6, synergy: { juggernaut: 3.5, bulwark: 2.0 } },
  { id: "wintersblessing", name: "Bénédiction d'Hiver", desc: "Ralentit les ennemis proches.",         tags: ["cc"],         baseWinrate: 50.2, synergy: { bulwark: 1.5 } },
  { id: "adrenaline",  name: "Adrénaline",         desc: "+Vitesse d'attaque en combat.",              tags: ["as"],         baseWinrate: 50.8, synergy: { deft: 3.0 } },
  { id: "deft",         name: "Habileté",           desc: "+Coups critiques.",                          tags: ["crit"],       baseWinrate: 51.3, synergy: { adrenaline: 3.0 } },
  { id: "arcanebolt",  name: "Trait Arcanique",    desc: "Les sorts appliquent une marque explosive.", tags: ["ap", "burst"],baseWinrate: 51.7, synergy: { glasscannon: 4.0, electrocute: 2.5 } },
  { id: "bulwark",     name: "Rempart",            desc: "Bouclier périodique.",                        tags: ["shield", "tank"], baseWinrate: 50.6, synergy: { fortification: 2.0, wintersblessing: 1.5 } },
  { id: "vampirism",   name: "Vampirisme",         desc: "+Vol de vie global.",                         tags: ["sustain"],    baseWinrate: 51.9, synergy: { juggernaut: 1.5, secondwind: 2.0 } },
];
